### PR TITLE
Fix bug where multiple insances of EventManager could exist

### PR DESCRIPTION
**Pull request by superdweebie**

### CODE REVIEW

**Comment by joshystuart** [comment]
All is well! Merging ;)

**Comment by joshystuart** [comment]
I'm still not getting the `create` event firing :( Is it a special event that's only present in `shard-module`?

**Comment by superdweebie** [comment]
:( Create is fired in here (not in `shard-module`): https://github.com/zoopcommerce/shard/blob/master/lib/Zoop/Shard/ODMCore/FlushSubscriber.php#L63

The FlushSubscriber listens to `mongodm-odm` events and translates them into shard events - my beginning attempts to abstract out doctrine from shard. So on a `dm->flush()` shard will find any documents marked for creation, and fire a `create` event, `validate` event, and `crypt` event.

**Comment by superdweebie** [comment]
I just had another thought. I haven't gone through your code carefully, but could you double check that you are calling flush on the right document manager. Two connections, with two manifests also means two document managers. For `create` to be called, the sage document must be persisted against the correct document manager, and then flush called against that document manager.

**Comment by joshystuart** [comment]
I'll point my profiler at https://github.com/zoopcommerce/shard/blob/master/lib/Zoop/Shard/ODMCore/FlushSubscriber.php#L63 to see what I can find.

I am definitely using the correct `DM` because they have different database settings. So the documents are created in the right db ie. they are created in the `shard_development` db, but they just aren't passing through the `create` listener (which means they are missing page technology traits).

I thought maybe I've missed some config somewhere. It worked fine when I was using just the `default` connection, so I have a feeling something isn't being pushed into the `commerce` and `sage` configs properly:  

**global**: https://github.com/crimsonronin/ZoopCommerce/blob/Feature/Sage/config/autoload/global.php

**dev**: https://github.com/crimsonronin/ZoopCommerce/blob/Feature/Sage/config/autoload/development.php

Am I missing anything from those?

**Comment by superdweebie** [comment]
Sorry, you're using `doctrine-mongo-odm-module` to configure and create the dm instances. I thought you were using shard stand alone with your own dm factory. In that case you definitely should use `shard-module`. The main thing `shard-module` does with all the config juggling is integrate with `doctinre-mongo-odm-module`. I'm downloading your branch to have a fiddle.

**Comment by joshystuart** [comment]
Thanks!

By the way, I'm not really using this config to create `doctrine-mongo-odm-module`:

``` php
'doctrine' => [
        'odm' => [
            'connection' => [
                'sage' => [
                    'dbname' => 'sage_production',
                    'server' => 'int.mongo.cbdc07d3feb6bc.scalr-dns.net',
                    'port' => '27017',
                    'user' => '',
                    'password' => '',
                ],
                'commerce' => [
                    'dbname' => 'zoop',
                    'server' => 'int.mongo.cbdc07d3feb6bc.scalr-dns.net',
                    'port' => '27017',
                    'user' => '',
                    'password' => '',
                ],
            ],
            'configuration' => [
                'sage' => [
                    'metadata_cache' => 'doctrine.cache.juggernaut.filesystem',
                    'generate_proxies' => false,
                    'proxy_dir' => __DIR__ . '/../../data/proxies',
                    'proxy_namespace' => 'proxies',
                    'generate_hydrators' => false,
                    'hydrator_dir' => __DIR__ . '/../../data/hydrators',
                    'hydrator_namespace' => 'hydrators',
                    'default_db' => 'sage_production',
                ],
                'commerce' => [
                    'metadata_cache' => 'doctrine.cache.juggernaut.filesystem',
                    'generate_proxies' => false,
                    'proxy_dir' => __DIR__ . '/../../data/proxies',
                    'proxy_namespace' => 'proxies',
                    'generate_hydrators' => false,
                    'hydrator_dir' => __DIR__ . '/../../data/hydrators',
                    'hydrator_namespace' => 'hydrators',
                    'default_db' => 'zoop',
                ]
            ],
        ],
    ],
```

I actually use it to create the manifest connections here:
https://github.com/crimsonronin/ZoopCommerce/blob/Feature/Sage/module/Commerce/src/Zoop/Legacy/Utils/Service/SageDocumentManagerFactory.php

There's a lot that has changed in this branch, so let me know if you have any trouble. The only place that requires the `create` listener is when accessing server side sage eg:

**AddToCart**
https://github.com/crimsonronin/ZoopCommerce/blob/Feature/Sage/public/commerce/CartController.php#L65

Which dispatches here: https://github.com/crimsonronin/ZoopCommerce/blob/Feature/Sage/module/Commerce/src/Zoop/Legacy/Sage/Helper/ServerSideTracker.php#L23

Which goes to the `Sage` server side `MongoDb` client here: https://github.com/crimsonronin/sage/blob/master/module/Sage/src/Zoop/Sage/Helper/Client/MongoDb.php#L49

**Comment by superdweebie** [comment]
My net connection is a little flaky at the moment - too flaky for a composer update to work properly.

However, I did notice, change this: https://github.com/crimsonronin/ZoopCommerce/blob/Feature/Sage/module/Commerce/src/Zoop/Legacy/Utils/Service/SageDocumentManagerFactory.php#L73 to this: https://github.com/zoopcommerce/shard/blob/master/lib/Zoop/Shard/ODMCore/DevDocumentManagerFactory.php#L66

**Comment by superdweebie** [comment]
Have you found anything from "I'll point my profiler at https://github.com/zoopcommerce/shard/blob/master/lib/Zoop/Shard/ODMCore/FlushSubscriber.php#L63 to see what I can find."?

**Comment by joshystuart** [comment]
Yeah I already did that but hadn't committed it yet. I noticed I had to
change it because I got a circular exception. Haha.

No worries. I'll pick this up in the morning with fresh eyes!

By the way, it's basically the last big hurdle. I have to implement the
checkout logging, but that's no big deal.

**Comment by joshystuart** [comment]
Sorry I didn't see this. Nah not yet. I had to go make dinner. Might not
get to it tonight now :(

**Comment by joshystuart** [comment]
We weren't even getting to https://github.com/zoopcommerce/shard/blob/master/lib/Zoop/Shard/ODMCore/FlushSubscriber.php#L45

Then a bolt of lightening........... `'extension.odmcore' => true,` was missing from the config!

I have to check if the listeners are being fired properly now.

**Comment by joshystuart** [comment]
HORAYYYYYYY!!!! We are back in action.

I think because we aren't using the `default` config, we need to explicitly define all the extensions to load. `default` compensated for that because it has some extensions already set.

**Comment by superdweebie** [comment]
Big smiles

**Pull request merged**
