### PR TITLE
Fix for AccessControl on embedded documents

### PR DESCRIPTION
**Pull request by superdweebie**

### CODE REVIEW

**Comment by joshystuart** [comment]
Nicely done sir.

**Comment by superdweebie** [comment]
Merge is done, should I retag, or wait?

**Comment by joshystuart** [comment]
Yeah I reckon. I can do it if you like.

**Comment by superdweebie** [comment]
Ta. shard-module will need to have the shard version bumped also.

**Comment by joshystuart** [comment]
Yeah cool. Just working on that now :D

**Pull request merged**
