### PR TITLE
Fixes update mode collections bug.

### LINKED ISSUE #19: Unserializer update mode not working with Collections
The unserializer does not correctly handle collections in `UPDATE` mode.

I have a patch coming in the next 5mins.

### PR DESCRIPTION
**Pull request by joshystuart**
Fixes #19:

Collections would not correctly update using the serializer in the following situations:
- Removing an item from the collection
- Adding a new item to the collection

### CODE REVIEW

**Comment by joshystuart** [comment]
`Cyclomatic Complexity of 11` boo haha

I'll fix that up.

**Comment by superdweebie** [comment]
Yep - I had numbers up to 24 before I did some refactoring! The code is much better for it.

Are you all good with fixing that? You know of cyclomatic complexity is calculated?

**Comment by joshystuart** [comment]
yeah. But now the class complexity is high because I added another function. :(

**Comment by joshystuart** [comment]
Do you have any thoughts on how I should handle that?

**Comment by superdweebie** [comment]
So the unserializer is too complex...

For now I'm happy to add a suppression like this: https://github.com/zoopcommerce/shard/blob/master/lib/Zoop/Shard/Manifest.php#L20. Sorry, I don't know the exact name of the error to suppress. You'll need to look it up in the phpmd source.

Then, could you raise a new issue to remove the suppression. I can do some refactoring at a later date to get rid of it.

**Comment by superdweebie** [comment]
The name of the phpmd rule you want to suppress will be in `phpdm/src/main/resources/rulesets/codesize.xml`

**Comment by joshystuart** [comment]
Thanks. Sounds like a good temporary solution, particularly because I'm really not sure how to make it any smaller.

I'll commit the updates soon.

**Pull request merged**
