### PR TITLE
Hotfix/Unserializer with passed document

### PR DESCRIPTION
**Pull request by joshystuart**
When updating or patching a document using the unserializer, and also passing in the original document, collections would not persist correctly. eg.

```
{
  "_id" : "6088b3b8158734499517cbca32f09743",
  "groups" : [{
      "name" : "groupA"
    }, {
      "name" : "groupB"
    }]
}
```

Then calling:

``` php
...
 $updated = $this->unserializer->fromArray(
            [
                'id' => $id,
                'groups' => []
            ],
            'Zoop\Shard\Test\Serializer\TestAsset\Document\User',
            $user
        );
...
```

Would still appear like the following **in the DB**:

```
{
  "_id" : "6088b3b8158734499517cbca32f09743",
  "groups" : [{
      "name" : "groupA"
    }, {
      "name" : "groupB"
    }]
}
```

However, it would appear correctly in `$updated`, and therefore giving a false positive in the tests.

I have updated the `UnserializeModeTest` to ensure all tests have a document explicitly passed in to ensure this problem is avoided. **Should we also have tests that don't pass `$user` in**?

Also, I'm not sure if my treatment was ok for this: https://github.com/crimsonronin/shard/blob/Hotfix/UnserializerWithPassedDocument/lib/Zoop/Shard/Serializer/Unserializer.php#L288

### CODE REVIEW

**Comment by joshystuart** [comment]
:( I forgot to run phpmd

Any suggestion on what I should do to reduce the number of methods?

It was because I added https://github.com/crimsonronin/shard/blob/Hotfix/UnserializerWithPassedDocument/lib/Zoop/Shard/Serializer/Unserializer.php#L288

**Comment by joshystuart** [comment]
Run `phpunit Zoop/Shard/Test/Serializer/UnserializeModeTest` to see the failed tests. It only happens on a `patch` on `Collection`.

If you prevent auto tear down of the DB you can see that it destroys the embedded document contents.

**Comment by superdweebie** [comment]
I'm back on this this morning. I think I know the problem.

**Comment by superdweebie** [comment]
Problem found and fixed. Patch on it's way.

**Pull request closed without merging**
