### PR TITLE
Fix service manager config so custom extensions work. Added tests. Fixed...

### PR DESCRIPTION
**Pull request by superdweebie**
... bug in ODMCore/Extension constructor.

### CODE REVIEW

**Comment by joshystuart** [comment]
Can we merge both this and the other PR? I'm waiting to be able to use it in Sage.

Also, how do we fix the travis bug?

**Comment by joshystuart** [comment]
Actually, mine is now passing.

**Comment by superdweebie** [comment]
Yep, lets merge them.

**Comment by joshystuart** [comment]
You can do the honours. :)

**Comment by joshystuart** [comment]
wooo!'
Thanks

**Pull request merged**
