### PR TITLE
Hotfix: EmbedOne Unserializer

### LINKED ISSUE #17: Unserializer Update/Patch with Abstract inheritance
I've ran into another problem when using abstracted classes and the unserializer.

**AbstractVariable.php**

``` php
<?php

namespace Zoop\Legacy\Promotion\DataModel\Discount\Variable;

//Annotation imports
use Doctrine\ODM\MongoDB\Mapping\Annotations as ODM;
use Zoop\Shard\Annotation\Annotations as Shard;

abstract class AbstractVariable
{

    /**
     * @ODM\String
     */
    protected $name;

    public function getName()
    {
        return $this->name;
    }

    public function setName($name)
    {
        $this->name = $name;
    }

    public function __toString()
    {
        return $this->getName();
    }

}
```

**Order.php**

``` php
<?php

namespace Zoop\Legacy\Promotion\DataModel\Discount\Variable;

//Annotation imports
use Doctrine\ODM\MongoDB\Mapping\Annotations as ODM;
use Zoop\Shard\Annotation\Annotations as Shard;

/**
 * @ODM\EmbeddedDocument
 */
class Order extends AbstractVariable implements VariableInterface
{

    /**
     * @ODM\String
     */
    protected $name = 'Order';

}
```

**PromotionController.php**

``` php
...
$promotion = $this->get($id, false);
if ($promotion) {
    $newPromotion = $this->getUnserializer()->fromArray($data, 'Zoop\Legacy\Promotion\DataModel\AbstractPromotion', $promotion);
}
...
```

**Error**

```
[01-Dec-2013 10:00:38 Australia/Melbourne] PHP Fatal error:  Cannot access protected property Zoop\Legacy\Promotion\DataModel\Discount\Variable\Order::$name in /mnt/www/zoop/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadataInfo.php on line 1381
[01-Dec-2013 10:00:38 Australia/Melbourne] PHP Stack trace:
[01-Dec-2013 10:00:38 Australia/Melbourne] PHP   1. {main}() /mnt/www/zoop/public/commerce/tests/Promotion/UnlimitedPromotion/UpdateUnserialize.php:0
[01-Dec-2013 10:00:38 Australia/Melbourne] PHP   2. Zoop\Legacy\Promotion\Controller\PromotionController->update() /mnt/www/zoop/public/commerce/tests/Promotion/UnlimitedPromotion/UpdateUnserialize.php:23
[01-Dec-2013 10:00:38 Australia/Melbourne] PHP   3. Zoop\Shard\Serializer\Unserializer->fromArray() /mnt/www/zoop/module/Commerce/src/Zoop/Legacy/Promotion/Controller/PromotionController.php:207
[01-Dec-2013 10:00:38 Australia/Melbourne] PHP   4. Zoop\Shard\Serializer\Unserializer->unserialize() /mnt/www/zoop/vendor/zoopcommerce/shard/lib/Zoop/Shard/Serializer/Unserializer.php:74
[01-Dec-2013 10:00:38 Australia/Melbourne] PHP   5. Zoop\Shard\Serializer\Unserializer->unserializeField() /mnt/www/zoop/vendor/zoopcommerce/shard/lib/Zoop/Shard/Serializer/Unserializer.php:137
[01-Dec-2013 10:00:38 Australia/Melbourne] PHP   6. Zoop\Shard\Serializer\Unserializer->unserializeCollection() /mnt/www/zoop/vendor/zoopcommerce/shard/lib/Zoop/Shard/Serializer/Unserializer.php:148
[01-Dec-2013 10:00:38 Australia/Melbourne] PHP   7. Zoop\Shard\Serializer\Unserializer->unserialize() /mnt/www/zoop/vendor/zoopcommerce/shard/lib/Zoop/Shard/Serializer/Unserializer.php:211
[01-Dec-2013 10:00:38 Australia/Melbourne] PHP   8. Zoop\Shard\Serializer\Unserializer->unserializeField() /mnt/www/zoop/vendor/zoopcommerce/shard/lib/Zoop/Shard/Serializer/Unserializer.php:137
[01-Dec-2013 10:00:38 Australia/Melbourne] PHP   9. Zoop\Shard\Serializer\Unserializer->unserializeSingleModel() /mnt/www/zoop/vendor/zoopcommerce/shard/lib/Zoop/Shard/Serializer/Unserializer.php:146
[01-Dec-2013 10:00:38 Australia/Melbourne] PHP  10. Zoop\Shard\Serializer\Unserializer->unserialize() /mnt/www/zoop/vendor/zoopcommerce/shard/lib/Zoop/Shard/Serializer/Unserializer.php:187
[01-Dec-2013 10:00:38 Australia/Melbourne] PHP  11. Zoop\Shard\Serializer\Unserializer->unserializeField() /mnt/www/zoop/vendor/zoopcommerce/shard/lib/Zoop/Shard/Serializer/Unserializer.php:137
[01-Dec-2013 10:00:38 Australia/Melbourne] PHP  12. Doctrine\ODM\MongoDB\Mapping\ClassMetadataInfo->setFieldValue() /mnt/www/zoop/vendor/zoopcommerce/shard/lib/Zoop/Shard/Serializer/Unserializer.php:154
[01-Dec-2013 10:00:38 Australia/Melbourne] PHP  13. ReflectionProperty->setValue() /mnt/www/zoop/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadataInfo.php:1381
```

So basically `Doctrine/ODM/MongoDB/Mapping/ClassMetadataInfo` is trying to access the variable directly rather than via getters/setters?

I haven't really dug into this a create deal, but thought you might have some idea?

### PR DESCRIPTION
**Pull request by joshystuart**
Fixes #17;

The following now works:
- Serialize and Unserialize EmbedOne with discriminatorMap
- Serialize and Unserialize EmbedOne with targetDocument

### CODE REVIEW

**Comment by superdweebie** [comment]
@crimsonronin fantastic. Patch looks great. You can see on the travis report (https://travis-ci.org/zoopcommerce/shard/jobs/14895632) that there are only a few CS fixes, and then the patch will be green and ready for merge.

**Comment by joshystuart** [comment]
Thanks yeah.

I was just going to run php /usr/local/bin/php-cs-fixer.phar fix /mnt/www/zoop/vendor/zoopcommerce/shard/tests  --level=psr2

Is that what you do? Or does it miss some things?

**Comment by superdweebie** [comment]
php-cs-fixer gets most things, but not everything.

Have a look in .travis.yml in shard's root directory. If you want, you can run the commands locally to check that phpcs will pass before pushing up to github and waiting for the travis job to finish.

**Comment by joshystuart** [comment]
So you just manually fix those then?

**Comment by superdweebie** [comment]
What I would do is run php-cs-fixer, then run phpcs locally, and fix the one or two things that php-cs-fixer missed by hand.

**Comment by joshystuart** [comment]
Sorry for my noobiness, but I don't have phpcs locally. Should I add it to my composer? Or how should I set this all up?

Currently I'm just working from my composer vendor directory in the Zoop repo. Should it be "stand alone"?

**Comment by superdweebie** [comment]
No problem with the questions. :)

If you composer install shard with development dependencies, then phpcs will be loaded for you (phpcs is `php_codesniffer` under `require-dev`). Then, from the tests directory you can just run the command from the travis.yml: `../vendor/bin/phpcs --standard=PSR2 ../lib/ ./Zoop/`.

**Comment by joshystuart** [comment]
Thanks. I'll give that a go.

**Comment by superdweebie** [comment]
Sorry if the automated code quality checks are annoying. It took me some time to bring the shard repo up to standard so they passed, but I think it has really been worth the effort.

**Comment by joshystuart** [comment]
It'd be good to try and automate some of these. Not sure if the netbeans formatter is customizable enough to do it, or if there's a plugin.

**Comment by superdweebie** [comment]
I haven't gone looking for a netbeans PSR02 formatter. There might be one out there.

**Comment by joshystuart** [comment]
`composer.phar install` should automatically pull the dev dependencies shouldn't it?

**Comment by superdweebie** [comment]
Yes. It should say `installing with dev dependencies ...` or something like that.

**Comment by joshystuart** [comment]
:S It's still not installing phpcs

```
Installing dependencies (including require-dev) from lock file
```

It's in my lock file too:

```
"require-dev": {
                "squizlabs/php_codesniffer": "1.4.*"
            },
```

**Comment by superdweebie** [comment]
Why not try a composer `update` to refresh everything, including the lock file?

**Comment by joshystuart** [comment]
Yeah I tried that first. I'll try again. 

**_First world composer problems**_

**Comment by superdweebie** [comment]
I'll give it a go my end.

**Comment by joshystuart** [comment]
No dice again. Might have something to do with composer cache?

**Comment by superdweebie** [comment]
I just did the following and it worked for me:

```
git clone http://github.com/zoopcommerce/shard
cd shard
composer.phar update
```

A batch file for phpcs is placed in `vendor/bin` and the sources live in `vendor/squizlabs/php_codesniffer`.

**Comment by joshystuart** [comment]
Ah, right. So you are working with a "stand alone" version of shard. I was working within my Zoop repo (as stated above).

I'll do that now and try again.

Thanks

**Comment by superdweebie** [comment]
Yes, that's the way to do it. You can place your 'stand alone' shard in `zoop/vendor/zoopcommerce/shard` so you have the best of both worlds.

**Comment by superdweebie** [comment]
BTW, when composer installs dev packages, it only installs dev packags in the root json. It doesn't install dev packages of dependencies - and if you think about it, that makes sense.

**Comment by joshystuart** [comment]
Yeah, that's what I was getting caught out on. They installed correctly as a "stand alone".
I'll fix and send updates through soon.

**Pull request merged**
